### ISSUE TITLE
Constant not found

### ISSUE THREAD

**Issue by santutunga** [SamranTariq/Whatsapp_Facebook_VideoSaver#1]
error when it open in android studio - **cannot find symbol variable Constant error**

how can it solve?

**Comment by SamranTariq** [comment]
### Thanks for your response
Code Updated, Take a look/download again and use it...

**OR**

Create a new file "Constant.java" and in this file add these lines
```
package com.example.whatsapp_facebook_videosaver;

class Constant {
    public static int nav_clicked = 0;
    public static Boolean isNavClicked = false;

    public static Boolean isToggle = true;
    public static int color = 0xff3b5998;
    public static int theme = R.style.AppTheme;
}
```
**Demo**

**Like this'**
![Error_Solved](https://user-images.githubusercontent.com/50068566/94512139-c6b15f00-0234-11eb-9ad1-d553cbd80ad8.png)

# BEST OF LUCK

**Comment by SamranTariq** [comment]
> error when it open in android studio - **cannot find symbol variable Constant error**
> 
> how can it solve?

### Thanks for your response
Code Updated, Take a look/download again and use it...

**OR**

Create a new file "Constant.java" and in this file add these lines
```
package com.example.whatsapp_facebook_videosaver;

class Constant {
    public static int nav_clicked = 0;
    public static Boolean isNavClicked = false;

    public static Boolean isToggle = true;
    public static int color = 0xff3b5998;
    public static int theme = R.style.AppTheme;
}
```
**Demo**

**Like this'**
![Error_Solved](https://user-images.githubusercontent.com/50068566/94512139-c6b15f00-0234-11eb-9ad1-d553cbd80ad8.png)

# BEST OF LUCK

**Comment by santutunga** [comment]
when I changed i face another issue in IntroActivity error

C:\Users\Rion\Desktop\Whatsapp_Facebook_VideoSaver-master\app\src\main\java\com\example\whatsapp_facebook_videosaver\IntroActivity.java:35: error: cannot find symbol
        SharedPreferences.Editor editor = getSharedPreferences(Constants.MyPREFERENCES, Context.MODE_PRIVATE).edit();
                                                               ^
  symbol:   variable Constants
  location: class IntroActivity

**Comment by santutunga** [comment]
when i created a java file then rebuild i face another issue



> Task :app:compileDebugJavaWithJavac FAILED
C:\Users\Rion\Desktop\Whatsapp_Facebook_VideoSaver-master\app\src\main\java\com\example\whatsapp_facebook_videosaver\IntroActivity.java:35: error: cannot find symbol
        SharedPreferences.Editor editor = getSharedPreferences(Constants.MyPREFERENCES, Context.MODE_PRIVATE).edit();
                                                                        ^
  symbol:   variable MyPREFERENCES
  location: class Constants
C:\Users\Rion\Desktop\Whatsapp_Facebook_VideoSaver-master\app\src\main\java\com\example\whatsapp_facebook_videosaver\onfacebook.java:92: error: cannot find symbol
        setTheme(Constant.theme);
                 ^
  symbol:   variable Constant
  location: class onfacebook
C:\Users\Rion\Desktop\Whatsapp_Facebook_VideoSaver-master\app\src\main\java\com\example\whatsapp_facebook_videosaver\onfacebook.java:112: error: cannot find symbol
        preferences = mainActivity.getSharedPreferences(Constants.MyPREFERENCES, Context.MODE_PRIVATE);
                                                                 ^
  symbol:   variable MyPREFERENCES
  location: class Constants
C:\Users\Rion\Desktop\Whatsapp_Facebook_VideoSaver-master\app\src\main\java\com\example\whatsapp_facebook_videosaver\onfacebook.java:308: error: cannot find symbol
                        Constants.FOLDER_NAME, fileN);
                                 ^
  symbol:   variable FOLDER_NAME
  location: class Constants
C:\Users\Rion\Desktop\Whatsapp_Facebook_VideoSaver-master\app\src\main\java\com\example\whatsapp_facebook_videosaver\onfacebook.java:394: error: cannot find symbol
                            Constants.FOLDER_NAME + fileN}, null,
                                     ^
  symbol:   variable FOLDER_NAME
  location: class Constants
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors

**Comment by santutunga** [comment]
the problem was solved. thank you
but the app was too many bug by using. please solve it

**Comment by SamranTariq** [comment]
> the problem was solved. thank you
> but the app was too many bug by using. please solve it

Application work properly in my device without any bug, i think i missed some files during upload this project on github, So Thanks for your feedback
**I'll try to update project files and check all files one by one**
